### ISSUE TITLE
Owlbot should keep track of custom modifications to templates

### ISSUE THREAD

**Issue by kolea2** [googleapis/synthtool#1798]
We have some examples of libraries that make modifications to otherwise standard templates. For example, https://github.com/googleapis/java-bigtable/blob/main/.kokoro/presubmit/integration.cfg#L9-L12 adds custom IT args to this standard template: https://github.com/googleapis/synthtool/blob/master/synthtool/gcp/templates/java_library/.kokoro/presubmit/integration.cfg. As such, we need to exclude it from owlbot and any new iterations of these templates need to be handled manually (see https://github.com/googleapis/java-bigtable/pull/1255 and fix https://github.com/googleapis/java-bigtable/pull/1258).

It would be great if owlbot could preserve known additions to templates so we can still receive updates without having to do manual work on them in a repeated way.

**Comment by kolea2** [comment]
Transferring to appropriate repo and reopening.

**Comment by suztomo** [comment]
The problem is that the granularity of owlbot.py exclusion logic (implemented by `java.common_templates(excludes=[ ...` ([usage link](https://github.com/googleapis/java-bigtable/blob/main/owlbot.py#LL97C1-L97C33)) is file-level and this is too coarse grained to meet this issue.

Rough idea 1: Somehow we use Git's merging capability.

Rough idea 2: INTEGRATION_TEST_ARGS to be in independent file that the build.sh reads if one exists.

**Comment by kolea2** [comment]
@suztomo just building off of your second idea a bit - something similar to https://github.com/googleapis/java-bigtable/blob/main/.readme-partials.yml which inserts custom things into our READMEs could work here as well. Would also work nicely if new environment variables need to be introduced in the future.

**Comment by suztomo** [comment]
Found that https://github.com/googleapis/synthtool/blob/master/synthtool/gcp/partials.py Thank you for information.

**Comment by suztomo** [comment]
In addition to INTEGRATION_TEST_ARGS, there are other environment variables that differ from the template: gcloud-devel BIGTABLE_TESTING_INSTANCE.

Now I'm feeing a solution similar to .readme-partials.yml is better to accommodate different needs

**Comment by kolea2** [comment]
@suztomo once https://github.com/googleapis/java-datastore/pull/1102/is merged, we will also have `DATASTORE_PROJECT_ID`. All to say, yes - there are env variables other than `INTEGRATION_TEST_ARGS` (and new ones can always be added in the future).

**Comment by suztomo** [comment]
# Idea of partial files for env_vars

`.kokoro/nightly/.samples.cfg.partials.yml`. In general its `.<cfg file name>.partials.yml`. The YAML file contains the following section:

```
env_vars:
  - key: INTEGRATION_TEST_ARGS
    value: "-P bigtable-emulator-it,bigtable-prod-it,bigtable-prod-batch-it -Dbigtable.project=gcloud-devel -Dbigtable.instance=google-cloud-bigtable -Dbigtable.table=integration-tests -Dbigtable.kms_key_name=projects/gcloud-devel/locations/us-east1/keyRings/cmek-test-key-ring/cryptoKeys/cmek-test-key -Dbigtable.wait-for-cmek-key-status=true"
  - key: DATASTORE_PROJECT_ID
    value: java-docs-samples-testing
```

When OwlBot post processor generates the templated file with ".cfg", it looks for  `.<cfg file name>.partials.yml` in the GitHub repository. If the partial YAML file exists, then it does the following to the generated file:

- If the template already has the key for `env_vars` , then it overrides the value.
- If the template does not have the key for the `env_vars`, then it adds a new `env_vars`.

**Comment by JoeWang1127** [comment]
@suztomo I found that [`load_partials`](https://github.com/googleapis/synthtool/blob/6444141a0ab125ff5579e0b697b41ccc500cbda7/synthtool/gcp/partials.py#L24) is called in [`common_templates`](https://github.com/googleapis/synthtool/blob/38ad6361919ddf1bbfbcc328ebc969f8d27763d7/synthtool/languages/java.py#L474) to load key-value pairs from partial files.

I can add an additional parameter to `common_templates`, called `partial_files` with default value, to load partials other than `.readme-partials.yml` or `.readme-partials.yaml` into the templates.

Then in owlbot.py, to load partials:
```
java.common_templates(
  excludes=[
    '.gitignore',
    '.kokoro/presubmit/integration.cfg',
    '.kokoro/presubmit/graalvm-native.cfg',
    '.kokoro/presubmit/graalvm-native-17.cfg',
  ],
  partial_files=[".kokoro/nightly/integration.cfg-partials.yaml"]
)
```

WDYT?

**Comment by suztomo** [comment]
@JoeWang1127 Good start. Before implementing it, would you write down what ".kokoro/nightly/integration.cfg-partials.yaml" would look like?

**Comment by suztomo** [comment]
@JoeWang1127 What about the difference between gcloud-devel proejct and java-docs-samples-testing project?

```
-  value: "gcloud-devel"
+  value: "java-docs-samples-testing"
```

**Comment by JoeWang1127** [comment]
The contents of partials can only be *inserted* into templates, so two env_vars can't be merged even if they have the same `key`.

**Comment by suztomo** [comment]
Good. Then the current [load_partials](https://github.com/googleapis/synthtool/blob/6444141a0ab125ff5579e0b697b41ccc500cbda7/synthtool/gcp/partials.py#L24) does not work good for the cfg files. Would you design something better? Start with an ideal `integration.cfg-partials.yaml` file.

**Comment by JoeWang1127** [comment]
I think `integration.cfg-partials.yaml` can be:
```
kokoro_nightly_integration:
  - key: "INTEGRATION_TEST_ARGS"
    value: "-P bigtable-emulator-it,bigtable-prod-it,bigtable-prod-batch-it -Dbigtable.project=gcloud-devel -Dbigtable.instance=google-cloud-bigtable -Dbigtable.table=integration-tests -Dbigtable.kms_key_name=projects/gcloud-devel/locations/us-east1/keyRings/cmek-test-key-ring/cryptoKeys/cmek-test-key -Dbigtable.wait-for-cmek-key-status=true"
  - key: "GCLOUD_PROJECT"
    value: "gcloud-devel"
```

If the key is not presented in the template, then the key-value pair is inserted to the template; otherwise the value will be overwritten. Something like you [mentioned](https://github.com/googleapis/synthtool/issues/1798#issuecomment-1579329373).

The template needs redesign and a new file `integration.cfg-default.yaml` to hold default key-value pairs.

**Comment by suztomo** [comment]
It reads as if it only takes care of envvars.

**Comment by JoeWang1127** [comment]
In the template, it says the format of integration.cfg is defined in `//devtools/kokoro/config/proto/build.proto`, but I can't find this file in google3.

If we need other keys besides `env_vars`, then `integration.cfg-partials.yaml` can be:
```
kokoro_nightly_integration:
    env_vars:
        - key: "INTEGRATION_TEST_ARGS"
          value: "-P bigtable-emulator-it,bigtable-prod-it,bigtable-prod-batch-it -Dbigtable.project=gcloud-devel -Dbigtable.instance=google-cloud-bigtable -Dbigtable.table=integration-tests -Dbigtable.kms_key_name=projects/gcloud-devel/locations/us-east1/keyRings/cmek-test-key-ring/cryptoKeys/cmek-test-key -Dbigtable.wait-for-cmek-key-status=true"
        - key: "GCLOUD_PROJECT"
          value: "gcloud-devel"
```
